name: CI

on:
  push:
    branches: [main, develop]
    tags: ['v*']          # enable release-on-tag
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  lint:
    name: Lint (StyLua + Selene)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash

      - name: Add Rokit to PATH
        run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH

      - name: Install tools
        run: rokit install --no-trust-check

      - name: Run StyLua
        run: stylua --check src/ tests/

      - name: Run Selene
        run: selene src/ tests/

  build:
    name: Rojo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash

      - name: Add Rokit to PATH
        run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH

      - name: Install tools
        run: rokit install --no-trust-check

      - name: Cache Wally
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/wally
            Packages
          key: wally-${{ runner.os }}-${{ hashFiles('wally.lock') }}
          restore-keys: |
            wally-${{ runner.os }}-

      - name: Wally install
        run: wally install

      - name: Build project
        run: rojo build default.project.json -o datum-serde.rbxm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: datum-serde
          path: datum-serde.rbxm

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write        # required to create releases
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: datum-serde

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: datum-serde.rbxm
          body: |
            ## datum-serde ${{ github.ref_name }}

            Type-safe data serialization, migration, and versioning for Roblox.

            ### Installation
            - Download `datum-serde.rbxm` and import into Roblox Studio
            - Or use Wally: `DatumSerde = "TuneScotty/datum-serde@${{ github.ref_name }}"`

            See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for usage.